# Generated by Django 5.0.3 on 2024-03-05 11:38

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='title', unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriler',
                'verbose_name_plural': 'Kategoriler',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detail', models.TextField()),
                ('image', models.ImageField(default='products.jpg', upload_to='news_products_image/', verbose_name='Ürün')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='title', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürünler',
                'verbose_name_plural': 'Ürünler',
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.products')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='web.CartItem', to='web.products'),
        ),
    ]
