# Generated by Django 5.0.3 on 2024-03-04 10:54

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='title', unique=True),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detail', models.TextField()),
                ('image', models.ImageField(default='products.jpg', upload_to='news_products_image/', verbose_name='Ürün')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='title', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürünler',
                'verbose_name_plural': 'Ürünler',
                'db_table': 'Products',
            },
        ),
    ]
